services:
  sql:
    image: postgres:16
    container_name: tournament-prediction-sql
    ports:
      # external: internal
      - 6789:6432
    volumes:
      - sql-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    restart: on-failure
    logging:
      options:
        max-size: 10m
        max-file: 3

volumes:
  sql-volume:
